"""把迷宮場地直接輸出成 Nav2 map_server 吃的 .pgm + .yaml。

為什麼要有這支 —— 它是「把問題切一半」的工具:

    走不到目標點的時候,原因只可能在兩邊之一 ——
      (a) 地圖本身爛掉(SLAM 畫歪、牆變雙線、有鬼影)
      (b) Nav2 參數不對(robot_radius 太大、inflation 太厚、costmap 設定錯)

    真車上這兩件事永遠糾纏在一起,因為你手上只有 SLAM 畫出來的那張圖。
    這支產生的是**幾何上完美**的地圖,拿它去跑 Nav2:
      還是走不了 -> 一定是 (b),去查 config/nav2_params.yaml
      正常走完   -> 一定是 (a),回頭去查 SLAM / 光達外參 / 里程計

    2026-07-28 那次「goal 一下就 abort」花了很久才找到是 robot_radius 0.11
    太大(最大連通區只剩 4.07 平方公尺)。有這支的話,第一輪就會指向 (b)。

輸出的 origin 和模擬世界原點一致,所以 Nav2 的 map 座標 = 模擬座標,
/sim/ground_truth 可以直接和 AMCL 的估計疊在一起看(見 fake_base_node 的
world_tf_mode:=identity)。

用法:
    python3 sim/tirt_sim/make_map.py sim/worlds/tirt_maze.yaml maps/sim_maze
    ./run_nav2.sh sim_maze
"""

import os
import sys

from tirt_sim.maze import load_world


def write_map(world, out_base, resolution=0.05):
    img = world.to_occupancy_png(resolution)
    h, w = img.shape

    pgm_path = out_base + '.pgm'
    yaml_path = out_base + '.yaml'

    # PGM 的第一列是影像**上緣**,對應世界座標的最大 y,所以要上下翻轉。
    # 弄反的話地圖會整個鏡像,而且症狀非常難認:AMCL 勉強收斂得到一個
    # 對稱位置,然後導航行為莫名其妙。
    with open(pgm_path, 'wb') as f:
        f.write(b'P5\n')
        f.write(b'# generated by sim/tirt_sim/make_map.py\n')
        f.write(f'{w} {h}\n255\n'.encode())
        f.write(img[::-1, :].tobytes())

    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(f'image: {os.path.basename(pgm_path)}\n')
        f.write('mode: trinary\n')
        f.write(f'resolution: {resolution}\n')
        f.write(f'origin: [{world.origin[0]}, {world.origin[1]}, 0.0]\n')
        f.write('negate: 0\n')
        f.write('occupied_thresh: 0.65\n')
        f.write('free_thresh: 0.25\n')

    return pgm_path, yaml_path, w, h


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        print('用法: python3 make_map.py <world.yaml> <輸出路徑不含副檔名> [解析度]')
        return 1
    world = load_world(sys.argv[1])
    out = sys.argv[2]
    res = float(sys.argv[3]) if len(sys.argv) > 3 else 0.05

    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    pgm, yml, w, h = write_map(world, out, res)
    print(f'場地「{world.name}」-> {w}x{h} 格 @ {res}m = '
          f'{w*res:.2f}x{h*res:.2f}m')
    print(f'  {pgm}')
    print(f'  {yml}')
    print(f'\n這是幾何完美的地圖(沒有 SLAM 誤差)。拿它跑 Nav2:')
    print(f'  ./run_nav2.sh {os.path.basename(out)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
